const fs=require("fs");
const OUT=[];
const a=s=>OUT.push(s);
a("import jsPDF from 'jspdf';");\na("import { Member, ProfitDistribution } from '@/contexts/OrganizationContext';");\na("import { formatDate } from '@/lib/utils';");\na('');
a('export interface ReportData {');
a('  members: Member[];');
a('  totalContributions: number;');
a('  totalLoans: number;');
a('  totalLoanRecovered: number;');
a('  reserveFund: number;');
a('  organizationName: string;');
a('  currentDate: string;');
a('}');
a('');
a('export interface Settings {');
a('  applyLoanInterest: boolean;');
a('  loanInterestRate: number;');
a('  organizationName: string;');
a('}');
